#!/usr/bin/env python3
"""Resumable direct-transcription evaluation for the Table-1 held-out states.

The protocol is deliberately matched to the final-paper evaluation:

* 128 componentwise random directions generated by torch seed 20260720;
* N_i(0) = 10 (1 + 0.20 Z_i);
* 800 intervalwise-ZOH controls and float64 RK4 with four substeps;
* physical objective weights (alpha, beta, gamma) = (1, 40, 8000), obtained
  by multiplying the repository's equivalent normalized objective by 400;
* one state-specific L-BFGS-B solve initialized from the locked nominal
  direct-transcription schedule; and
* R_sing on T_32 intersected with [1.5, 8), using the same DOP853
  state/costate reconstruction and analytic scalar identities as the final
  supplement's nominal and resistant-heavy direct rows.

Each state is written atomically and can be resumed independently.  Invoke
several workers with disjoint ``--worker-index`` values, then run
``--aggregate-only`` once all samples are present.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import math
import os
import sys
import time
from dataclasses import asdict
from pathlib import Path
from typing import Any

os.environ.setdefault("OMP_NUM_THREADS", "1")
os.environ.setdefault("MKL_NUM_THREADS", "1")
os.environ.setdefault("OPENBLAS_NUM_THREADS", "1")
os.environ.setdefault("NUMEXPR_NUM_THREADS", "1")

import numpy as np
import torch
from scipy.optimize import minimize


ROOT = Path(__file__).resolve().parents[1]
for search_path in (ROOT, ROOT / "scripts"):
    if str(search_path) not in sys.path:
        sys.path.insert(0, str(search_path))

from scripts.direct_rk4_discrete_adjoint import (  # noqa: E402
    RK4ZOHDiscreteAdjoint,
    TumorObjective,
)
from scripts.generate_three_case_hamiltonian_results import (  # noqa: E402
    RealizedCase,
    evaluate_case,
)
from scripts.run_time_loss_family_ablation import make_cfg  # noqa: E402
from scripts.train_feedback_section5 import (  # noqa: E402
    make_fixed_directions,
    test_states_from_directions,
)
from train_paper_pmp_kkt import build_params  # noqa: E402
from tumor_problem import TumorProblem  # noqa: E402


PHYSICAL_SCALE = 400.0
PHYSICAL_PROBLEM = TumorProblem(
    T=10.0,
    m=21,
    umax=3.0,
    beta=40.0,
    alpha=1.0,
    gamma=8000.0,
    n0=10.0,
    m_suppression=0.5,
)


def safe(value: Any) -> Any:
    if isinstance(value, Path):
        return str(value)
    if isinstance(value, np.ndarray):
        return value.tolist()
    if isinstance(value, np.generic):
        return value.item()
    if isinstance(value, dict):
        return {str(key): safe(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [safe(item) for item in value]
    return value


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def load_direct(path: Path, n: int) -> np.ndarray:
    with np.load(path, allow_pickle=False) as pack:
        key = "interval_u" if "interval_u" in pack else "u"
        control = np.asarray(pack[key], dtype=np.float64).reshape(-1)
    if control.size == n + 1:
        control = control[:-1]
    if control.size != n:
        raise ValueError(f"{path}: expected {n} controls, found {control.size}")
    return np.clip(control, 0.0, 3.0)


def value_and_gradient(
    control: np.ndarray,
    initial_state: torch.Tensor,
    evaluator: RK4ZOHDiscreteAdjoint,
) -> tuple[float, np.ndarray]:
    return evaluator.value_and_gradient(
        np.asarray(control, dtype=np.float64),
        initial_state.detach().cpu().numpy().astype(np.float64),
    )


def projected_gradient(
    control: np.ndarray, gradient: np.ndarray, upper: float
) -> np.ndarray:
    return control - np.clip(control - gradient, 0.0, upper)


def direct_singular_metrics(
    control: np.ndarray,
    initial_state: np.ndarray,
    *,
    diagnostic_points: int,
    interior_start: float,
    interior_end: float,
    rtol: float,
    atol: float,
) -> dict[str, float]:
    breakpoints = np.linspace(
        0.0, PHYSICAL_PROBLEM.T, control.size + 1, dtype=np.float64
    )
    specification = RealizedCase(
        "direct",
        "Direct transcription",
        Path("state_specific_direct.npz"),
        None,
        breakpoints,
        control,
    )
    dense_time = np.linspace(
        0.0, PHYSICAL_PROBLEM.T, diagnostic_points, dtype=np.float64
    )
    evaluated = evaluate_case(
        specification,
        dense_time,
        initial_state,
        PHYSICAL_PROBLEM,
        rtol=rtol,
        atol=atol,
    )
    mask = (dense_time >= interior_start) & (dense_time < interior_end)
    if not np.any(mask):
        raise RuntimeError("empty singular diagnostic interval")

    def rms(key: str) -> float:
        values = np.asarray(evaluated.quantities[key], dtype=np.float64)[mask]
        return float(np.sqrt(np.mean(values * values)))

    rms_hu = rms("psi")
    rms_dot = rms("dot_psi")
    rms_ddot = rms("ddot_psi")
    return {
        "rms_H_u": rms_hu,
        "rms_dH_u_dt": rms_dot,
        "rms_d2H_u_dt2": rms_ddot,
        "R_sing": float(
            math.sqrt(rms_hu**2 + rms_dot**2 + rms_ddot**2)
        ),
        "identity_max_abs": float(max(evaluated.identity_errors.values())),
    }


def protocol(args: argparse.Namespace, cfg: Any) -> dict[str, Any]:
    return {
        "schema": "table1-direct-heldout-r020-v2-exact-discrete-adjoint",
        "direct_source": str(args.direct.resolve()),
        "direct_sha256": sha256(args.direct),
        "problem_normalized": asdict(cfg),
        "physical_objective_scale": PHYSICAL_SCALE,
        "physical_weights": {
            "alpha": 1.0,
            "beta": 40.0,
            "gamma": 8000.0,
        },
        "sample_count": args.samples,
        "direction_seed": args.seed,
        "radius": args.radius,
        "substeps": args.substeps,
        "optimizer": {
            "method": "two-stage L-BFGS-B",
            "start": "locked nominal direct-transcription schedule",
            "gradient": (
                "exact discrete adjoint of the matching RK4-ZOH objective"
            ),
            "coarse_substeps": args.coarse_substeps,
            "coarse_maxiter": args.coarse_maxiter,
            "coarse_maxfun": args.coarse_maxfun,
            "fine_substeps": args.substeps,
            "fine_maxiter": args.fine_maxiter,
            "fine_maxfun": args.fine_maxfun,
            "ftol": args.ftol,
            "gtol": args.gtol,
            "maxls": args.maxls,
            "maxcor": args.maxcor,
        },
        "diagnostic": {
            "points": args.diagnostic_points,
            "grid": "T_32" if args.diagnostic_points == 25601 else "uniform",
            "interior": [args.interior_start, args.interior_end],
            "rtol": args.rtol,
            "atol": args.atol,
            "policy_semantics": "n=800 left-endpoint zero-order hold",
        },
    }


def signature(payload: dict[str, Any]) -> str:
    encoded = json.dumps(
        safe(payload), sort_keys=True, separators=(",", ":")
    ).encode()
    return hashlib.sha256(encoded).hexdigest()


def atomic_json(path: Path, payload: dict[str, Any]) -> None:
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(
        json.dumps(safe(payload), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    temporary.replace(path)


def solve_sample(
    sample: int,
    state: torch.Tensor,
    direction: torch.Tensor,
    nominal_control: np.ndarray,
    cfg: Any,
    evaluators: dict[int, RK4ZOHDiscreteAdjoint],
    args: argparse.Namespace,
    protocol_signature: str,
) -> dict[str, Any]:
    samples_dir = args.out_dir / "samples"
    samples_dir.mkdir(parents=True, exist_ok=True)
    json_path = samples_dir / f"sample_{sample:04d}.json"
    npz_path = samples_dir / f"sample_{sample:04d}.npz"
    if args.resume and json_path.is_file() and npz_path.is_file():
        cached = json.loads(json_path.read_text(encoding="utf-8"))
        if cached.get("protocol_signature") == protocol_signature:
            return cached

    sample_started = time.perf_counter()
    initial_J, initial_gradient = value_and_gradient(
        nominal_control, state, evaluators[args.substeps]
    )
    initial_mapping = projected_gradient(
        nominal_control, initial_gradient, cfg.umax
    )

    coarse_started = time.perf_counter()
    coarse_result = minimize(
        lambda control: value_and_gradient(
            control, state, evaluators[args.coarse_substeps]
        ),
        nominal_control,
        method="L-BFGS-B",
        jac=True,
        bounds=[(0.0, cfg.umax)] * cfg.n,
        options={
            "maxiter": args.coarse_maxiter,
            "maxfun": args.coarse_maxfun,
            "ftol": args.ftol,
            "gtol": args.gtol,
            "maxls": args.maxls,
            "maxcor": args.maxcor,
        },
    )
    coarse_seconds = time.perf_counter() - coarse_started
    coarse_control = np.clip(
        np.asarray(coarse_result.x, dtype=np.float64), 0.0, cfg.umax
    )
    coarse_fine_objective, _ = value_and_gradient(
        coarse_control, state, evaluators[args.substeps]
    )

    fine_started = time.perf_counter()
    fine_result = minimize(
        lambda control: value_and_gradient(
            control, state, evaluators[args.substeps]
        ),
        coarse_control,
        method="L-BFGS-B",
        jac=True,
        bounds=[(0.0, cfg.umax)] * cfg.n,
        options={
            "maxiter": args.fine_maxiter,
            "maxfun": args.fine_maxfun,
            "ftol": args.ftol,
            "gtol": args.gtol,
            "maxls": args.maxls,
            "maxcor": args.maxcor,
        },
    )
    fine_seconds = time.perf_counter() - fine_started
    fine_control = np.clip(
        np.asarray(fine_result.x, dtype=np.float64), 0.0, cfg.umax
    )
    fine_objective, fine_gradient = value_and_gradient(
        fine_control, state, evaluators[args.substeps]
    )

    if initial_J <= min(coarse_fine_objective, fine_objective) + 1.0e-14:
        control = nominal_control.copy()
        objective = initial_J
        gradient = initial_gradient
        mapping = initial_mapping
        selected = "unoptimized_nominal_direct"
    elif coarse_fine_objective <= fine_objective + 1.0e-14:
        control = coarse_control
        objective, gradient = value_and_gradient(
            control, state, evaluators[args.substeps]
        )
        mapping = projected_gradient(control, gradient, cfg.umax)
        selected = "coarse_L-BFGS-B"
    else:
        control = fine_control
        objective = fine_objective
        gradient = fine_gradient
        mapping = projected_gradient(control, gradient, cfg.umax)
        selected = "coarse_to_fine_L-BFGS-B"
    optimizer_seconds = coarse_seconds + fine_seconds

    diagnostic_started = time.perf_counter()
    diagnostics = direct_singular_metrics(
        control,
        state.detach().cpu().numpy().astype(np.float64),
        diagnostic_points=args.diagnostic_points,
        interior_start=args.interior_start,
        interior_end=args.interior_end,
        rtol=args.rtol,
        atol=args.atol,
    )
    diagnostic_seconds = time.perf_counter() - diagnostic_started

    temporary_npz = npz_path.with_suffix(".tmp.npz")
    np.savez_compressed(
        temporary_npz,
        sample=np.asarray(sample),
        direction=direction.detach().cpu().numpy(),
        N0=state.detach().cpu().numpy(),
        t=np.linspace(0.0, cfg.T, cfg.n + 1, dtype=np.float64),
        u=control,
        gradient=gradient,
        projected_gradient=mapping,
        J_normalized=np.asarray(objective),
        J_physical=np.asarray(PHYSICAL_SCALE * objective),
        rms_H_u=np.asarray(diagnostics["rms_H_u"]),
        rms_dH_u_dt=np.asarray(diagnostics["rms_dH_u_dt"]),
        rms_d2H_u_dt2=np.asarray(diagnostics["rms_d2H_u_dt2"]),
        R_sing=np.asarray(diagnostics["R_sing"]),
    )
    temporary_npz.replace(npz_path)

    row = {
        "sample": sample,
        "protocol_signature": protocol_signature,
        "selected": selected,
        "N0_mean": float(state.mean()),
        "N0_std": float(state.std(unbiased=False)),
        "N0_min": float(state.min()),
        "N0_max": float(state.max()),
        "J_initial_physical": PHYSICAL_SCALE * initial_J,
        "J_physical": PHYSICAL_SCALE * objective,
        "objective_improvement": PHYSICAL_SCALE * (initial_J - objective),
        "initial_projected_gradient_linf": float(
            np.max(np.abs(initial_mapping))
        ),
        "projected_gradient_linf": float(np.max(np.abs(mapping))),
        "projected_gradient_rms": float(
            np.sqrt(np.mean(mapping * mapping))
        ),
        "optimizer_success": bool(fine_result.success),
        "optimizer_status": int(fine_result.status),
        "optimizer_message": str(fine_result.message),
        "optimizer_nit": int(coarse_result.nit + fine_result.nit),
        "optimizer_nfev": int(coarse_result.nfev + fine_result.nfev),
        "optimizer_njev": int(
            getattr(coarse_result, "njev", coarse_result.nfev)
            + getattr(fine_result, "njev", fine_result.nfev)
        ),
        "coarse_success": bool(coarse_result.success),
        "coarse_status": int(coarse_result.status),
        "coarse_message": str(coarse_result.message),
        "coarse_nit": int(coarse_result.nit),
        "coarse_nfev": int(coarse_result.nfev),
        "coarse_seconds": coarse_seconds,
        "coarse_fine_evaluation_J_physical": (
            PHYSICAL_SCALE * coarse_fine_objective
        ),
        "fine_success": bool(fine_result.success),
        "fine_status": int(fine_result.status),
        "fine_message": str(fine_result.message),
        "fine_nit": int(fine_result.nit),
        "fine_nfev": int(fine_result.nfev),
        "fine_seconds": fine_seconds,
        "optimizer_seconds": optimizer_seconds,
        "diagnostic_seconds": diagnostic_seconds,
        "elapsed_seconds": time.perf_counter() - sample_started,
        **diagnostics,
        "artifact": str(npz_path.resolve()),
    }
    atomic_json(json_path, row)
    return row


def statistics(values: np.ndarray) -> dict[str, float]:
    values = np.asarray(values, dtype=np.float64)
    return {
        "mean": float(np.mean(values)),
        "sample_std": float(np.std(values, ddof=1)),
        "median": float(np.median(values)),
        "min": float(np.min(values)),
        "max": float(np.max(values)),
        "q05": float(np.quantile(values, 0.05)),
        "q95": float(np.quantile(values, 0.95)),
    }


def aggregate(args: argparse.Namespace, payload: dict[str, Any]) -> None:
    protocol_signature = signature(payload)
    rows = []
    for sample in range(args.samples):
        path = args.out_dir / "samples" / f"sample_{sample:04d}.json"
        if not path.is_file():
            raise FileNotFoundError(path)
        row = json.loads(path.read_text(encoding="utf-8"))
        if row.get("protocol_signature") != protocol_signature:
            raise ValueError(f"{path}: protocol signature mismatch")
        rows.append(row)

    fields = list(rows[0])
    with (args.out_dir / "per_sample.csv").open(
        "w", encoding="utf-8", newline=""
    ) as stream:
        writer = csv.DictWriter(stream, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)

    packed = []
    for sample in range(args.samples):
        path = args.out_dir / "samples" / f"sample_{sample:04d}.npz"
        if not path.is_file():
            raise FileNotFoundError(path)
        with np.load(path, allow_pickle=False) as source:
            packed.append(
                {
                    key: np.asarray(source[key])
                    for key in (
                        "direction",
                        "N0",
                        "u",
                        "gradient",
                        "projected_gradient",
                    )
                }
            )
    combined_path = args.out_dir / "direct_heldout_results.npz"
    temporary_combined = combined_path.with_suffix(".tmp.npz")
    np.savez_compressed(
        temporary_combined,
        sample=np.arange(args.samples, dtype=np.int64),
        directions=np.stack([item["direction"] for item in packed]),
        N0=np.stack([item["N0"] for item in packed]),
        u=np.stack([item["u"] for item in packed]),
        gradient=np.stack([item["gradient"] for item in packed]),
        projected_gradient=np.stack(
            [item["projected_gradient"] for item in packed]
        ),
        J_physical=np.asarray(
            [row["J_physical"] for row in rows], dtype=np.float64
        ),
        R_sing=np.asarray(
            [row["R_sing"] for row in rows], dtype=np.float64
        ),
        rms_H_u=np.asarray(
            [row["rms_H_u"] for row in rows], dtype=np.float64
        ),
        rms_dH_u_dt=np.asarray(
            [row["rms_dH_u_dt"] for row in rows], dtype=np.float64
        ),
        rms_d2H_u_dt2=np.asarray(
            [row["rms_d2H_u_dt2"] for row in rows], dtype=np.float64
        ),
        protocol_signature=np.asarray(protocol_signature),
    )
    temporary_combined.replace(combined_path)

    def array(key: str) -> np.ndarray:
        return np.asarray([row[key] for row in rows], dtype=np.float64)

    summary = {
        "protocol": payload,
        "protocol_signature": protocol_signature,
        "sample_count": len(rows),
        "J_physical": statistics(array("J_physical")),
        "R_sing": statistics(array("R_sing")),
        "rms_H_u": statistics(array("rms_H_u")),
        "rms_dH_u_dt": statistics(array("rms_dH_u_dt")),
        "rms_d2H_u_dt2": statistics(array("rms_d2H_u_dt2")),
        "projected_gradient_linf": statistics(
            array("projected_gradient_linf")
        ),
        "objective_improvement": statistics(
            array("objective_improvement")
        ),
        "optimizer_seconds": statistics(array("optimizer_seconds")),
        "diagnostic_seconds": statistics(array("diagnostic_seconds")),
        "elapsed_seconds": statistics(array("elapsed_seconds")),
        "summed_worker_seconds": float(np.sum(array("elapsed_seconds"))),
        "optimizer_success_count": int(
            sum(bool(row["optimizer_success"]) for row in rows)
        ),
        "selected_counts": {
            label: sum(row["selected"] == label for row in rows)
            for label in sorted({row["selected"] for row in rows})
        },
        "projected_gradient_pass_1e5_count": int(
            np.sum(array("projected_gradient_linf") <= 1.0e-5)
        ),
        "identity_max_abs": float(np.max(array("identity_max_abs"))),
        "artifacts": {
            "per_sample": str(
                (args.out_dir / "per_sample.csv").resolve()
            ),
            "samples": str((args.out_dir / "samples").resolve()),
            "combined": str(combined_path.resolve()),
            "combined_sha256": sha256(combined_path),
        },
    }
    atomic_json(args.out_dir / "summary.json", summary)
    print(json.dumps(summary, indent=2, sort_keys=True), flush=True)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--direct", type=Path, required=True)
    parser.add_argument("--out-dir", type=Path, required=True)
    parser.add_argument("--samples", type=int, default=128)
    parser.add_argument("--seed", type=int, default=20260720)
    parser.add_argument("--radius", type=float, default=0.20)
    parser.add_argument("--coarse-substeps", type=int, default=1)
    parser.add_argument("--substeps", type=int, default=4)
    parser.add_argument("--coarse-maxiter", type=int, default=120)
    parser.add_argument("--coarse-maxfun", type=int, default=260)
    parser.add_argument("--fine-maxiter", type=int, default=10)
    parser.add_argument("--fine-maxfun", type=int, default=80)
    parser.add_argument("--ftol", type=float, default=0.0)
    parser.add_argument("--gtol", type=float, default=1.0e-10)
    parser.add_argument("--maxls", type=int, default=60)
    parser.add_argument("--maxcor", type=int, default=40)
    parser.add_argument("--diagnostic-points", type=int, default=25601)
    parser.add_argument("--interior-start", type=float, default=1.5)
    parser.add_argument("--interior-end", type=float, default=8.0)
    parser.add_argument("--rtol", type=float, default=1.0e-10)
    parser.add_argument("--atol", type=float, default=1.0e-12)
    parser.add_argument("--workers", type=int, default=1)
    parser.add_argument("--worker-index", type=int, default=0)
    parser.add_argument(
        "--resume", action=argparse.BooleanOptionalAction, default=True
    )
    parser.add_argument("--aggregate-only", action="store_true")
    args = parser.parse_args()

    args.direct = args.direct.expanduser().resolve()
    args.out_dir = args.out_dir.expanduser().resolve()
    args.out_dir.mkdir(parents=True, exist_ok=True)
    if not 0 <= args.worker_index < args.workers:
        raise ValueError("worker-index must lie in [0, workers)")
    if args.diagnostic_points != 25601:
        raise ValueError("the final Table-1 protocol requires T_32 (25601 points)")

    torch.set_num_threads(1)
    torch.set_num_interop_threads(1)
    cfg = make_cfg(800)
    payload = protocol(args, cfg)
    protocol_signature = signature(payload)
    protocol_path = args.out_dir / "protocol.json"
    if protocol_path.is_file():
        existing = json.loads(protocol_path.read_text(encoding="utf-8"))
        if existing.get("protocol_signature") != protocol_signature:
            raise ValueError("existing output directory uses a different protocol")
    else:
        atomic_json(
            protocol_path,
            {"protocol_signature": protocol_signature, **payload},
        )

    if args.aggregate_only:
        aggregate(args, payload)
        return

    params = build_params(cfg, torch.device("cpu"), torch.float64)
    normalized_problem = TumorObjective.from_mapping(
        params, T=cfg.T, umax=cfg.umax
    )
    evaluators = {
        substeps: RK4ZOHDiscreteAdjoint(
            normalized_problem, cfg.n, substeps=substeps
        )
        for substeps in sorted({args.coarse_substeps, args.substeps})
    }
    nominal_control = load_direct(args.direct, cfg.n)
    directions = make_fixed_directions(
        args.samples, cfg.m, args.seed, torch.float64
    )
    states = test_states_from_directions(
        directions,
        args.radius,
        cfg,
        torch.device("cpu"),
        torch.float64,
    )
    assigned = [
        sample
        for sample in range(args.samples)
        if sample % args.workers == args.worker_index
    ]
    for position, sample in enumerate(assigned, start=1):
        started = time.perf_counter()
        row = solve_sample(
            sample,
            states[sample],
            directions[sample],
            nominal_control,
            cfg,
            evaluators,
            args,
            protocol_signature,
        )
        print(
            f"[worker {args.worker_index:02d}] "
            f"{position:03d}/{len(assigned):03d} sample={sample:03d} "
            f"J={row['J_physical']:.6f} "
            f"R={row['R_sing']:.6g} "
            f"PG={row['projected_gradient_linf']:.3e} "
            f"wall={time.perf_counter() - started:.2f}s",
            flush=True,
        )


if __name__ == "__main__":
    main()
